In [24]:
#Data Cleaning in Pandas
import pandas as pd
df = pd.read_excel(r"C:\Users\Admin\Desktop\Data Analyst  Project\Python\Data Cleaning in Pandas\Customer Call List.xlsx")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [25]:
df=df.drop_duplicates()
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [26]:
df=df.drop(columns="Not_Useful_Column")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [27]:
df["Last_Name"].str.strip()

0         Baggins
1           Nadir
2          /White
3         Schrute
4            Snow
5         Swanson
6          Winger
7          Holmes
8             NaN
9          Parker
10         Gamgee
11      ...Potter
12         Draper
13          Knope
14    Flenderson_
15        Weasley
16          Scott
17           Kent
18         Braton
19      Skywalker
Name: Last_Name, dtype: object

In [9]:
df["Last_Name"].str.strip("...")

0         Baggins
1           Nadir
2          /White
3         Schrute
4            Snow
5         Swanson
6          Winger
7          Holmes
8             NaN
9          Parker
10         Gamgee
11         Potter
12         Draper
13          Knope
14    Flenderson_
15        Weasley
16          Scott
17           Kent
18         Braton
19      Skywalker
Name: Last_Name, dtype: object

In [10]:
df["Last_Name"].str.strip("/")

0         Baggins
1           Nadir
2           White
3         Schrute
4            Snow
5         Swanson
6          Winger
7          Holmes
8             NaN
9          Parker
10         Gamgee
11      ...Potter
12         Draper
13          Knope
14    Flenderson_
15        Weasley
16          Scott
17           Kent
18         Braton
19      Skywalker
Name: Last_Name, dtype: object

In [31]:
df["Last_Name"]= df["Last_Name"].str.lstrip("...")
df["Last_Name"]= df["Last_Name"].str.lstrip("/")
df["Last_Name"]= df["Last_Name"].str.rstrip("_")

df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [35]:
#you can put all in one string 
df["Last_Name"]= df["Last_Name"].str.rstrip("123._/")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [49]:
df["Phone_Number"].str.replace('[^a-zA-Z0-9]','')
#df["Phone_Number"] = df["Phone_Number"].apply(lambda x: str(x))
#df ["Phone_Number"].apply(lambda x: x[0:3] +'-'+ x[3:6] + '-' + x[6:10])

C:\Users\Admin\AppData\Local\Temp\ipykernel_22944\578390125.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df["Phone_Number"].str.replace('[^a-zA-Z0-9]','')

0     1235455421
1     1236439775
2            nan
3     1235432345
4     8766783469
5     3047622467
6            nan
7     8766783469
8             Na
9     1235455421
10           nan
11           nan
12    1235432345
13    8766783469
14    3047622467
15    1235455421
16    1236439775
17           nan
18            Na
19    8766783469
Name: Phone_Number, dtype: object

In [52]:
 #changing to number to string
    df["Phone_Number"].apply(lambda x: str(x))

0     1235455421
1     1236439775
2            nan
3     1235432345
4     8766783469
5     3047622467
6            nan
7     8766783469
8             Na
9     1235455421
10           nan
11           nan
12    1235432345
13    8766783469
14    3047622467
15    1235455421
16    1236439775
17           nan
18            Na
19    8766783469
Name: Phone_Number, dtype: object

In [53]:
df ["Phone_Number"].apply(lambda x: x[0:3] +'-'+ x[3:6] + '-' + x[6:10])

0     123-545-5421
1     123-643-9775
2            nan--
3     123-543-2345
4     876-678-3469
5     304-762-2467
6            nan--
7     876-678-3469
8             Na--
9     123-545-5421
10           nan--
11           nan--
12    123-543-2345
13    876-678-3469
14    304-762-2467
15    123-545-5421
16    123-643-9775
17           nan--
18            Na--
19    876-678-3469
Name: Phone_Number, dtype: object

In [55]:
#df["Phone_Number"]=df["Phone_Number"].str.replace('[^a-zA-Z0-9]','')
#df["Phone_Number"] = df["Phone_Number"].apply(lambda x: str(x))
df["Phone_Number"] =df ["Phone_Number"].apply(lambda x: x[0:3] +'-'+ x[3:6] + '-' + x[6:10])
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123--54-5-54,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123--64-3-97,93 West Main Street,No,Yes
2,1003,Walter,White,nan----,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123--54-3-23,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876--67-8-34,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304--76-2-24,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,nan----,1209 South Street,No,No
7,1008,Sherlock,Holmes,876--67-8-34,98 Clue Drive,N,No
8,1009,Gandalf,NaN,Na----,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123--54-5-54,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,nan----,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,nan----,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123--54-3-23,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876--67-8-34,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304--76-2-24,214 HR Avenue,N,No
15,1016,Ron,Weasley,123--54-5-54,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123--64-3-97,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,nan----,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,Na----,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876--67-8-34,"910 Tatooine Road, Tatooine",Yes,N

In [57]:
#get rid of nan na
df["Phone_Number"]=df["Phone_Number"].str.replace('nan--','')
df["Phone_Number"]=df["Phone_Number"].str.replace('Na--','')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123--54-5-54,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123--64-3-97,93 West Main Street,No,Yes
2,1003,Walter,White,--,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123--54-3-23,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876--67-8-34,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304--76-2-24,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,--,1209 South Street,No,No
7,1008,Sherlock,Holmes,876--67-8-34,98 Clue Drive,N,No
8,1009,Gandalf,NaN,--,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123--54-5-54,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,--,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123--54-3-23,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876--67-8-34,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304--76-2-24,214 HR Avenue,N,No
15,1016,Ron,Weasley,123--54-5-54,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123--64-3-97,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,--,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,--,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876--67-8-34,"910 Tatooine Road, Tatooine",Yes,N

In [66]:
#address
df[["Street_Address","State","Zip_Code"]] = df["Address"].str.split(',',2,expand=True)
df

C:\Users\Admin\AppData\Local\Temp\ipykernel_22944\4067343554.py:2: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  df[["Street_Address","State","Zip_Code"]] = df["Address"].str.split(',',2,expand=True)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip_Code,Street_Address
0,1001,Frodo,Baggins,123--54-5-54,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,None,123 Shire Lane
1,1002,Abed,Nadir,123--64-3-97,93 West Main Street,No,Yes,93 West Main Street,None,None,93 West Main Street
2,1003,Walter,White,--,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None,298 Drugs Driveway
3,1004,Dwight,Schrute,123--54-3-23,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,Pennsylvania,18503,980 Paper Avenue
4,1005,Jon,Snow,876--67-8-34,123 Dragons Road,Y,No,123 Dragons Road,None,None,123 Dragons Road
5,1006,Ron,Swanson,304--76-2-24,768 City Parkway,Yes,Yes,768 City Parkway,None,None,768 City Parkway
6,1007,Jeff,Winger,--,1209 South Street,No,No,1209 South Street,None,None,1209 South Street
7,1008,Sherlock,Holmes,876--67-8-34,98 Clue Drive,N,No,98 Clue Drive,None,None,98 Clue Drive
8,1009,Gandalf,NaN,--,123 Middle Earth,Yes,NaN,123 Middle Earth,None,None,123 Middle Earth
9,1010,Peter,Parker,123--54-5-54,"25th Main Street, New York",Yes,No,25th Main Street,New York,None,25th Main Street
10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,None,612 Shire Lane
11,1012,Harry,Potter,--,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None,2394 Hogwarts Avenue
12,1013,Don,Draper,123--54-3-23,2039 Main Street,Yes,N,2039 Main Street,None,None,2039 Main Street
13,1014,Leslie,Knope,876--67-8-34,343 City Parkway,Yes,No,343 City Parkway,None,None,343 City Parkway
14,1015,Toby,Flenderson,304--76-2-24,214 HR Avenue,N,No,214 HR Avenue,None,None,214 HR Avenue
15,1016,Ron,Weasley,123--54-5-54,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,None,None,2395 Hogwarts Avenue
16,1017,Michael,Scott,123--64-3-97,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,None,121 Paper Avenue
17,1018,Clark,Kent,--,3498 Super Lane,Y,NaN,3498 Super Lane,None,None,3498 Super Lane
18,1019,Creed,Braton,--,N/a,N/a,Yes,N/a,None,None,N/a
19,1020,Anakin,Skywalker,876--67-8-34,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,None,910 Tatooine Road

In [70]:
df["Paying Customer"]=df["Paying Customer"].str.replace('Yes','Y')
df["Paying Customer"]=df["Paying Customer"].str.replace('No','N')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip_Code,Street_Address
0,1001,Frodo,Baggins,123--54-5-54,"123 Shire Lane, Shire",Y,No,123 Shire Lane,Shire,None,123 Shire Lane
1,1002,Abed,Nadir,123--64-3-97,93 West Main Street,N,Yes,93 West Main Street,None,None,93 West Main Street
2,1003,Walter,White,--,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None,298 Drugs Driveway
3,1004,Dwight,Schrute,123--54-3-23,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503,980 Paper Avenue
4,1005,Jon,Snow,876--67-8-34,123 Dragons Road,Y,No,123 Dragons Road,None,None,123 Dragons Road
5,1006,Ron,Swanson,304--76-2-24,768 City Parkway,Y,Yes,768 City Parkway,None,None,768 City Parkway
6,1007,Jeff,Winger,--,1209 South Street,N,No,1209 South Street,None,None,1209 South Street
7,1008,Sherlock,Holmes,876--67-8-34,98 Clue Drive,N,No,98 Clue Drive,None,None,98 Clue Drive
8,1009,Gandalf,NaN,--,123 Middle Earth,Y,NaN,123 Middle Earth,None,None,123 Middle Earth
9,1010,Peter,Parker,123--54-5-54,"25th Main Street, New York",Y,No,25th Main Street,New York,None,25th Main Street
10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Y,No,612 Shire Lane,Shire,None,612 Shire Lane
11,1012,Harry,Potter,--,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None,2394 Hogwarts Avenue
12,1013,Don,Draper,123--54-3-23,2039 Main Street,Y,N,2039 Main Street,None,None,2039 Main Street
13,1014,Leslie,Knope,876--67-8-34,343 City Parkway,Y,No,343 City Parkway,None,None,343 City Parkway
14,1015,Toby,Flenderson,304--76-2-24,214 HR Avenue,N,No,214 HR Avenue,None,None,214 HR Avenue
15,1016,Ron,Weasley,123--54-5-54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None,2395 Hogwarts Avenue
16,1017,Michael,Scott,123--64-3-97,"121 Paper Avenue, Pennsylvania",Y,No,121 Paper Avenue,Pennsylvania,None,121 Paper Avenue
17,1018,Clark,Kent,--,3498 Super Lane,Y,NaN,3498 Super Lane,None,None,3498 Super Lane
18,1019,Creed,Braton,--,N/a,N/a,Yes,N/a,None,None,N/a
19,1020,Anakin,Skywalker,876--67-8-34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None,910 Tatooine Road

In [75]:
#df= df.replace('N/a','')
#df= df.replace('NaN','')
df=df.fillna('')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip_Code,Street_Address
0,1001,Frodo,Baggins,123--54-5-54,"123 Shire Lane, Shire",Y,No,123 Shire Lane,Shire,,123 Shire Lane
1,1002,Abed,Nadir,123--64-3-97,93 West Main Street,N,Yes,93 West Main Street,,,93 West Main Street
2,1003,Walter,White,--,298 Drugs Driveway,N,,298 Drugs Driveway,,,298 Drugs Driveway
3,1004,Dwight,Schrute,123--54-3-23,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503,980 Paper Avenue
4,1005,Jon,Snow,876--67-8-34,123 Dragons Road,Y,No,123 Dragons Road,,,123 Dragons Road
5,1006,Ron,Swanson,304--76-2-24,768 City Parkway,Y,Yes,768 City Parkway,,,768 City Parkway
6,1007,Jeff,Winger,--,1209 South Street,N,No,1209 South Street,,,1209 South Street
7,1008,Sherlock,Holmes,876--67-8-34,98 Clue Drive,N,No,98 Clue Drive,,,98 Clue Drive
8,1009,Gandalf,,--,123 Middle Earth,Y,,123 Middle Earth,,,123 Middle Earth
9,1010,Peter,Parker,123--54-5-54,"25th Main Street, New York",Y,No,25th Main Street,New York,,25th Main Street
10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Y,No,612 Shire Lane,Shire,,612 Shire Lane
11,1012,Harry,Potter,--,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,,2394 Hogwarts Avenue
12,1013,Don,Draper,123--54-3-23,2039 Main Street,Y,N,2039 Main Street,,,2039 Main Street
13,1014,Leslie,Knope,876--67-8-34,343 City Parkway,Y,No,343 City Parkway,,,343 City Parkway
14,1015,Toby,Flenderson,304--76-2-24,214 HR Avenue,N,No,214 HR Avenue,,,214 HR Avenue
15,1016,Ron,Weasley,123--54-5-54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,,2395 Hogwarts Avenue
16,1017,Michael,Scott,123--64-3-97,"121 Paper Avenue, Pennsylvania",Y,No,121 Paper Avenue,Pennsylvania,,121 Paper Avenue
17,1018,Clark,Kent,--,3498 Super Lane,Y,,3498 Super Lane,,,3498 Super Lane
18,1019,Creed,Braton,--,N/a,N/a,Yes,N/a,,,N/a
19,1020,Anakin,Skywalker,876--67-8-34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,,910 Tatooine Road

In [78]:
for x in df.index:
    if df.loc[x,'Do_Not_Contact']=='Y':
        df.drop(x,inplace=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip_Code,Street_Address
0,1001,Frodo,Baggins,123--54-5-54,"123 Shire Lane, Shire",Y,No,123 Shire Lane,Shire,,123 Shire Lane
1,1002,Abed,Nadir,123--64-3-97,93 West Main Street,N,Yes,93 West Main Street,,,93 West Main Street
2,1003,Walter,White,--,298 Drugs Driveway,N,,298 Drugs Driveway,,,298 Drugs Driveway
4,1005,Jon,Snow,876--67-8-34,123 Dragons Road,Y,No,123 Dragons Road,,,123 Dragons Road
5,1006,Ron,Swanson,304--76-2-24,768 City Parkway,Y,Yes,768 City Parkway,,,768 City Parkway
6,1007,Jeff,Winger,--,1209 South Street,N,No,1209 South Street,,,1209 South Street
7,1008,Sherlock,Holmes,876--67-8-34,98 Clue Drive,N,No,98 Clue Drive,,,98 Clue Drive
8,1009,Gandalf,,--,123 Middle Earth,Y,,123 Middle Earth,,,123 Middle Earth
9,1010,Peter,Parker,123--54-5-54,"25th Main Street, New York",Y,No,25th Main Street,New York,,25th Main Street
10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Y,No,612 Shire Lane,Shire,,612 Shire Lane
11,1012,Harry,Potter,--,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,,2394 Hogwarts Avenue
12,1013,Don,Draper,123--54-3-23,2039 Main Street,Y,N,2039 Main Street,,,2039 Main Street
13,1014,Leslie,Knope,876--67-8-34,343 City Parkway,Y,No,343 City Parkway,,,343 City Parkway
14,1015,Toby,Flenderson,304--76-2-24,214 HR Avenue,N,No,214 HR Avenue,,,214 HR Avenue
15,1016,Ron,Weasley,123--54-5-54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,,2395 Hogwarts Avenue
16,1017,Michael,Scott,123--64-3-97,"121 Paper Avenue, Pennsylvania",Y,No,121 Paper Avenue,Pennsylvania,,121 Paper Avenue
17,1018,Clark,Kent,--,3498 Super Lane,Y,,3498 Super Lane,,,3498 Super Lane
18,1019,Creed,Braton,--,N/a,N/a,Yes,N/a,,,N/a
19,1020,Anakin,Skywalker,876--67-8-34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,,910 Tatooine Road

In [80]:

for x in df.index:
    if df.loc[x,'Phone_Number']=='':
        df.drop(x,inplace=True)
df
#df.dropna(subset="Phone_Number"),inplace=True) another way to drop values

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip_Code,Street_Address
0,1001,Frodo,Baggins,123--54-5-54,"123 Shire Lane, Shire",Y,No,123 Shire Lane,Shire,,123 Shire Lane
1,1002,Abed,Nadir,123--64-3-97,93 West Main Street,N,Yes,93 West Main Street,,,93 West Main Street
2,1003,Walter,White,--,298 Drugs Driveway,N,,298 Drugs Driveway,,,298 Drugs Driveway
4,1005,Jon,Snow,876--67-8-34,123 Dragons Road,Y,No,123 Dragons Road,,,123 Dragons Road
5,1006,Ron,Swanson,304--76-2-24,768 City Parkway,Y,Yes,768 City Parkway,,,768 City Parkway
6,1007,Jeff,Winger,--,1209 South Street,N,No,1209 South Street,,,1209 South Street
7,1008,Sherlock,Holmes,876--67-8-34,98 Clue Drive,N,No,98 Clue Drive,,,98 Clue Drive
8,1009,Gandalf,,--,123 Middle Earth,Y,,123 Middle Earth,,,123 Middle Earth
9,1010,Peter,Parker,123--54-5-54,"25th Main Street, New York",Y,No,25th Main Street,New York,,25th Main Street
10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Y,No,612 Shire Lane,Shire,,612 Shire Lane
11,1012,Harry,Potter,--,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,,2394 Hogwarts Avenue
12,1013,Don,Draper,123--54-3-23,2039 Main Street,Y,N,2039 Main Street,,,2039 Main Street
13,1014,Leslie,Knope,876--67-8-34,343 City Parkway,Y,No,343 City Parkway,,,343 City Parkway
14,1015,Toby,Flenderson,304--76-2-24,214 HR Avenue,N,No,214 HR Avenue,,,214 HR Avenue
15,1016,Ron,Weasley,123--54-5-54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,,2395 Hogwarts Avenue
16,1017,Michael,Scott,123--64-3-97,"121 Paper Avenue, Pennsylvania",Y,No,121 Paper Avenue,Pennsylvania,,121 Paper Avenue
17,1018,Clark,Kent,--,3498 Super Lane,Y,,3498 Super Lane,,,3498 Super Lane
18,1019,Creed,Braton,--,N/a,N/a,Yes,N/a,,,N/a
19,1020,Anakin,Skywalker,876--67-8-34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,,910 Tatooine Road

In [81]:
df=df.reset_index(drop=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street Address,State,Zip_Code,Street_Address
0,1001,Frodo,Baggins,123--54-5-54,"123 Shire Lane, Shire",Y,No,123 Shire Lane,Shire,,123 Shire Lane
1,1002,Abed,Nadir,123--64-3-97,93 West Main Street,N,Yes,93 West Main Street,,,93 West Main Street
2,1003,Walter,White,--,298 Drugs Driveway,N,,298 Drugs Driveway,,,298 Drugs Driveway
3,1005,Jon,Snow,876--67-8-34,123 Dragons Road,Y,No,123 Dragons Road,,,123 Dragons Road
4,1006,Ron,Swanson,304--76-2-24,768 City Parkway,Y,Yes,768 City Parkway,,,768 City Parkway
5,1007,Jeff,Winger,--,1209 South Street,N,No,1209 South Street,,,1209 South Street
6,1008,Sherlock,Holmes,876--67-8-34,98 Clue Drive,N,No,98 Clue Drive,,,98 Clue Drive
7,1009,Gandalf,,--,123 Middle Earth,Y,,123 Middle Earth,,,123 Middle Earth
8,1010,Peter,Parker,123--54-5-54,"25th Main Street, New York",Y,No,25th Main Street,New York,,25th Main Street
9,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Y,No,612 Shire Lane,Shire,,612 Shire Lane
10,1012,Harry,Potter,--,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,,2394 Hogwarts Avenue
11,1013,Don,Draper,123--54-3-23,2039 Main Street,Y,N,2039 Main Street,,,2039 Main Street
12,1014,Leslie,Knope,876--67-8-34,343 City Parkway,Y,No,343 City Parkway,,,343 City Parkway
13,1015,Toby,Flenderson,304--76-2-24,214 HR Avenue,N,No,214 HR Avenue,,,214 HR Avenue
14,1016,Ron,Weasley,123--54-5-54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,,2395 Hogwarts Avenue
15,1017,Michael,Scott,123--64-3-97,"121 Paper Avenue, Pennsylvania",Y,No,121 Paper Avenue,Pennsylvania,,121 Paper Avenue
16,1018,Clark,Kent,--,3498 Super Lane,Y,,3498 Super Lane,,,3498 Super Lane
17,1019,Creed,Braton,--,N/a,N/a,Yes,N/a,,,N/a
18,1020,Anakin,Skywalker,876--67-8-34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,,910 Tatooine Road